# Generated by Django 5.0.6 on 2024-07-11 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='comuna',
            new_name='comuna_cod',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='propietario',
            new_name='propietario_rut',
        ),
    ]
