# Generated by Django 5.0.6 on 2024-07-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_comuna_inmueble_comuna_cod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='comuna_cod',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='propietario_rut',
            new_name='propietario',
        ),
    ]
