# Generated by Django 5.0.6 on 2024-07-24 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='precios',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='precios_ufs',
            new_name='precio_ufs',
        ),
        migrations.AlterField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comunas', to='main.region'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('bodega', 'Bodega'), ('parcela', 'Parcela')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('arrendador', 'Arrendador'), ('arrendatario', 'Arrendatario'), ('admin', 'Admin')], default='arrendatario', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
